version: '3'
services:
  db:
    container_name: generator-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - $PWD/src/dev_schema.sql:/docker-entrypoint-initdb.d/schema.sql
