version: '3'
services:
  generator-app:
    container_name: generator-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:8000

  db:
    container_name: generator-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - $PWD/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  proxy:
    container_name: proxy
    image: nginx:alpine
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/certs:/etc/nginx/certs/
    ports:
      - 443:443
