CREATE TABLE meals (id SERIAL PRIMARY KEY, name TEXT);
CREATE TABLE users (id SERIAL PRIMARY KEY, username UNIQUE TEXT, password TEXT);
--CREATE TABLE menus (id SERIAL PRIMARY KEY, meal_ids INTEGER REFERENCES meals, user_id INTEGER REFERENCES users, date DATE);
CREATE TABLE menus (id SERIAL PRIMARY KEY, meal_ids INTEGER[], user_id INTEGER, date DATETIME);