
name: CI

on:
  push:
    branches:
      - masteri
      - developmentti
  pull_request:
    branches:
      - master
      - development
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pylint
        run: pylint src --rcfile=".pylintrc"
      - name: Run tests
        run: coverage run --branch -m pytest src
      - name: Coverage report
        run: coverage xml
      - name: Coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
